Discord:
  BotToken: 'YOUR_BOT_TOKEN'
Database:
  host: 'localhost'
  port: 3306
  user: 'root'
  password: 'root'
  database: 'mtserverbot'
Domains:
  -
      ZoneId: ''
      Domain: 'mtserver.nl'
      AuthEmail: ''
      AuthKey: ''
#  -
#    ZoneId: ''
#    Domain: 'eenanderedomeinnaam.nl'
#    AuthEmail: ''
#    AuthKey: ''